PB-664 Client (#397)
* init commit

* original use statement

* summer skeleton

* recursive async fn problem

* rudimentary error handling

* minor formatting

* extra docstring

* polling mechanism with interval

* no need to save pk from round_params

* 1 round integration test

* remove spurious comments

* spawn service; fewer clients; print stmts

* fixes post-rebase; reinstate coord kickstart; minor tidy

* minor doc fix

* tidy prints

* tracer_subscriber dep; temp workaround to kickstart; temp tweak of select ratios

* fix crash

Fixes the following crash:

```
thread 'tokio-runtime-worker' panicked at 'slice index starts at 64 but ends at 0', src/message/message.rs:140:36
/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  13: core::slice::slice_index_order_fail
             at src/libcore/slice/mod.rs:2758
  14: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index_mut
             at /rustc/f93bb2a50b37bc8bafe4d960e2afd839eaa854ed/src/libcore/slice/mod.rs:2927
  15: <core::ops::range::RangeFrom<usize> as core::slice::SliceIndex<[T]>>::index_mut
             at /rustc/f93bb2a50b37bc8bafe4d960e2afd839eaa854ed/src/libcore/slice/mod.rs:3001
  16: core::slice::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /rustc/f93bb2a50b37bc8bafe4d960e2afd839eaa854ed/src/libcore/slice/mod.rs:2743
  17: <alloc::vec::Vec<T> as core::ops::index::IndexMut<I>>::index_mut
             at /rustc/f93bb2a50b37bc8bafe4d960e2afd839eaa854ed/src/liballoc/vec.rs:1954
  18: xain_fl::message::message::MessageSeal::sign
             at src/message/message.rs:140
  19: xain_fl::message::message::MessageSeal::seal
             at src/message/message.rs:122
  20: xain_fl::participant::Participant::seal_message
             at src/participant.rs:168
  21: xain_fl::participant::Participant::compose_sum_message
             at src/participant.rs:126
  22: xain_fl::client::Client::summer::{{closure}}
             at ./src/client.rs:137
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f93bb2a50b37bc8bafe4d960e2afd839eaa854ed/src/libcore/future/mod.rs:73
  24: xain_fl::client::Client::per_round::{{closure}}
             at ./src/client.rs:120

...
```

* coordinator: add logs

* use the same dummy config for the coordinator and participants

* fix test

What we get from the coordinator is a portion of the seed dict, not
the entire seed dict.

* fix get_seeds and test_get_seeds

* reduce clients to 10 in test drive

* more logging in client

* rename per_round to during_round

* make participant pk pub(crate), remove getter

* log another deserialize error

* revert select ratios

* typo in docstring

* rustfmt

* rustfmt again

* updated docstring with more rationale

* change dummy mask_model weights to match dummy_config bound type B0

Co-authored-by: little-dude <corentinhenry@gmail.com>